name: Create Pull Request via GitHub API

on:
  push:

permissions:
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request via API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_DATA=$(jq -n \
                    --arg title "Automated Pull Request DO NOT DO THIS AT HOME" \
                    --arg body "This is an automated pull request." \
                    --arg head "do-not-do-this-at-home" \
                    --arg base "main" \
                    '{title: $title, body: $body, head: $head, base: $base}')
          curl \
            -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "$PR_DATA"